sudo: required
dist: trusty
language: cpp
compiler: gcc
env:
  global:
  - APT_DEPENDENCIES="gccxml doxygen doxygen-latex libboost-all-dev"
  - DEBSIGN_KEYID=5AE5CD75
notifications:
  email:
  - idh-devel@lirmm.fr
branches:
  only:
  - master
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y gccxml
  - curDir=`pwd`; cd "$build_dir"; wget https://pybindgen.googlecode.com/files/pybindgen-0.16.0.tar.bz2; tar -xvjf ./pybindgen-0.16.0.tar.bz2; cd pybindgen-0.16.0; ./waf configure; ./waf; sudo ./waf install; cd $curDir
  - ./.travis/run  before_install
  - ./.travis/dependencies/eigen-3.2
