dist: trusty
language: python
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - g++
    - cmake
script:
- . ./.travis/common.sh
- pip install .
- nosetests
before_install:
- ./.travis/dependencies/eigen-3.2
- pip install -r requirements.txt
notifications:
  slack:
    secure: AQEc0L8IPw0G+61qoFZ4ceGVuKP6G+XO9UQpoeAbL4IMwJvTsFtbSerFH9lQih2OEz3+iV1muEye9ISW1GuUIyJReQfZNI+sSpCYfxDTeDDdUseMqpFRp0KazVAAhPNZ+zADANKwMisofwQmBhwz0w+LSZ34nhj0Gm7/OGxiU2E=
